---
# - include:  1_prerequisites.yml
#   tags:
#   - seafile_prerequisites

- include:  2_provision.yml
  tags:
  - seafile_provision

# - include:  3_download.yml
#   tags:
#   - seafile_download

- include:  4_preconfigure.yml
  tags:
  - seafile_preconfigure
  - seafile_configure

- include:  5_configure.yml
  tags:
  - seafile_configure

- include:  6_customize.yml
  tags:
  - seafile_customize

- include:  7_database.yml
  tags:
  - seafile_database

- include:  8_init_admin.yml
  tags:
  - seafile_init_admin

- include:  9_init.yml
  tags:
  - seafile_init

- debug:
    msg: >
            If you upgraded seafile, please verify if you need to run some upgrade scripts manually.
            Have a look at the scripts in {{ seafile_latest_dir }}/upgrade
            and see http://manual.seafile.com/deploy/upgrade.html
  tags:
  - seafile
